package app.auf.ui

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF00696D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF17AFB4)
val onPrimaryContainerLight = Color(0xFF003C3E)
val secondaryLight = Color(0xFF635E50)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFEDE5D3)
val onSecondaryContainerLight = Color(0xFF6B6658)
val tertiaryLight = Color(0xFF9B2F99)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF27DEA)
val onTertiaryContainerLight = Color(0xFF710072)
val errorLight = Color(0xFFAA1935)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFCC354B)
val onErrorContainerLight = Color(0xFFFFF0F0)
val backgroundLight = Color(0xFFF5F5F5)
val onBackgroundLight = Color(0xFF171717)
val surfaceLight = Color(0xFFFCFCFC)
val onSurfaceLight = Color(0xFF1C1C1C)
val surfaceVariantLight = Color(0xFFD7E5E5)
val onSurfaceVariantLight = Color(0xFF3C4949)
val outlineLight = Color(0xFF6C7A7A)
val outlineVariantLight = Color(0xFFBBC9C9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313030)
val inverseOnSurfaceLight = Color(0xFFF4F0EF)
val inversePrimaryLight = Color(0xFF58D8DD)
val surfaceDimLight = Color(0xFFDDD9D9)
val surfaceBrightLight = Color(0xFFFCF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F3F2)
val surfaceContainerLight = Color(0xFFF1EDEC)
val surfaceContainerHighLight = Color(0xFFEBE7E7)
val surfaceContainerHighestLight = Color(0xFFE5E2E1)

// ── Extended semantic colors (not part of Material 3 core scheme) ──────────
// Warning/caution: used for permission danger levels, escalation indicators,
// and anywhere a "proceed with care" semantic is needed.
val warningLight = Color(0xFFAB6800)
val onWarningLight = Color(0xFFFFFFFF)
val warningContainerLight = Color(0xFFFFDDB0)
val onWarningContainerLight = Color(0xFF372100)

val primaryDark = Color(0xFF58D8DD)
val onPrimaryDark = Color(0xFF003739)
val primaryContainerDark = Color(0xFF17AFB4)
val onPrimaryContainerDark = Color(0xFF003C3E)
val secondaryDark = Color(0xFFFFFFFF)
val onSecondaryDark = Color(0xFF343024)
val secondaryContainerDark = Color(0xFFEAE2D0)
val onSecondaryContainerDark = Color(0xFF696456)
val tertiaryDark = Color(0xFFFFAAF4)
val onTertiaryDark = Color(0xFF5B005C)
val tertiaryContainerDark = Color(0xFFF27DEA)
val onTertiaryContainerDark = Color(0xFF710072)
val errorDark = Color(0xFFFF666B)
val onErrorDark = Color(0xFF680019)
val errorContainerDark = Color(0xFF49151C)
val onErrorContainerDark = Color(0xFFFFF0F0)
val backgroundDark = Color(0xFF0F0F0F)
val onBackgroundDark = Color(0xFFDEDEDE)
val surfaceDark = Color(0xFF141313)
val onSurfaceDark = Color(0xFFE5E2E1)
val surfaceVariantDark = Color(0xFF3C4949)
val onSurfaceVariantDark = Color(0xFFBBC9C9)
val outlineDark = Color(0xFF869393)
val outlineVariantDark = Color(0xFF3C4949)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E1)
val inverseOnSurfaceDark = Color(0xFF313030)
val inversePrimaryDark = Color(0xFF00696D)
val surfaceDimDark = Color(0xFF141313)
val surfaceBrightDark = Color(0xFF3A3939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1C1B1B)
val surfaceContainerDark = Color(0xFF201F1F)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFF353434)

// ── Extended semantic colors (dark) ───────────────────────────────────────
val warningDark = Color(0xFFFFB94D)
val onWarningDark = Color(0xFF5A3C00)
val warningContainerDark = Color(0xFF3D2700)
val onWarningContainerDark = Color(0xFFFFDDB0)