package app.auf.test

import app.auf.core.Action
import app.auf.core.Feature
import app.auf.core.FeatureState
import app.auf.core.Identity
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

// --- Test-only doubles for validating the builder ---
private data class FakeStateA(val value: String = "") : FeatureState
private class FakeFeatureA : Feature {
    override val identity = Identity(
        uuid = null, localHandle = "fakea", handle = "fakea", name = "FakeA"
    )
    override val composableProvider: Feature.ComposableProvider? = null
    override fun reducer(state: FeatureState?, action: Action): FeatureState? {
        if (state == null) {
            return FakeStateA()
        }
        return state
    }
}

private data class FakeStateB(val count: Int = 0) : FeatureState
private class FakeFeatureB : Feature {
    override val identity = Identity(
        uuid = null, localHandle = "fakeb", handle = "fakeb", name = "FakeB"
    )
    override val composableProvider: Feature.ComposableProvider? = null
    override fun reducer(state: FeatureState?, action: Action): FeatureState? {
        if (state == null) {
            return FakeStateB()
        }
        return state
    }
}

/**
 * Tier 1 Unit Test for the TestEnvironment builder itself, per P-TEST-003.
 */
class TestEnvironmentTest {

    @Test
    fun `build should include specified features`() {
        // ARRANGE
        val harness = TestEnvironment.create()
            .withFeature(FakeFeatureA())
            .withFeature(FakeFeatureB())
            .build()

        // Wrap test assertions to get automatic logging on failure.
        harness.runAndLogOnFailure {
            // ACT
            val initialFeatureStates = harness.store.state.value.featureStates.keys

            // ASSERT
            assertTrue(initialFeatureStates.contains("core"), "CoreFeature state should be present.")
            assertTrue(initialFeatureStates.contains("fakea"), "FakeFeatureA state should be present.")
            assertTrue(initialFeatureStates.contains("fakeb"), "FakeFeatureB state should be present.")
            assertEquals(3, initialFeatureStates.size, "Should include state slices for the two fake features plus Core.")
        }
    }

    @Test
    fun `build should inject specified initial state`() {
        // ARRANGE
        val harness = TestEnvironment.create()
            .withFeature(FakeFeatureA())
            .withInitialState("fakea", FakeStateA("initial value"))
            .build()

        harness.runAndLogOnFailure {
            // ACT
            val stateSlice = harness.store.state.value.featureStates["fakea"] as? FakeStateA

            // ASSERT
            assertNotNull(stateSlice)
            assertEquals("initial value", stateSlice.value)
        }
    }

    @Test
    fun `build should create default state for features without specified initial state`() {
        // ARRANGE
        val harness = TestEnvironment.create()
            .withFeature(FakeFeatureA())
            .withFeature(FakeFeatureB())
            .withInitialState("fakea", FakeStateA("initial value"))
            .build()

        harness.runAndLogOnFailure {
            // ACT
            val stateSliceA = harness.store.state.value.featureStates["fakea"] as? FakeStateA
            val stateSliceB = harness.store.state.value.featureStates["fakeb"] as? FakeStateB

            // ASSERT
            assertNotNull(stateSliceA)
            assertEquals("initial value", stateSliceA.value)
            assertNotNull(stateSliceB)
            assertEquals(0, stateSliceB.count)
        }
    }

    @Test
    fun `build should automatically include CoreFeature and its state`() {
        val harness = TestEnvironment.create().withFeature(FakeFeatureA()).build()
        harness.runAndLogOnFailure {
            assertNotNull(harness.store.state.value.featureStates["core"])
        }
    }

    @Test
    fun `build should default to using the autogenerated ActionRegistry`() {
        // ARRANGE
        val harness = TestEnvironment.create().build()

        harness.runAndLogOnFailure {
            // ACT
            harness.store.dispatch("ui", Action("core.SET_ACTIVE_VIEW", buildJsonObject { put("key", "test") }))
            harness.store.dispatch("ui", Action("unknown.ACTION"))

            // ASSERT
            val validAction = harness.processedActions.find { it.name == "core.SET_ACTIVE_VIEW" }
            assertNotNull(validAction, "A known valid action from the registry should be present.")
            val invalidAction = harness.processedActions.find { it.name == "unknown.ACTION" }
            assertNull(invalidAction, "An unknown action should be blocked by the Store.")
            val log = harness.platform.capturedLogs.find { it.message.contains("Unknown Action") }
            assertNotNull(log, "The store should log a security violation for the unknown action.")
        }
    }

    @Test
    fun `withActionRegistry() successfully overrides the default registry`() {
        // ARRANGE: Use a minimal override registry. Only these action names will be valid.
        val minimalRegistry = setOf("system.STARTING", "fakea.ALLOWED")
        val harness = TestEnvironment.create()
            .withActionRegistry(minimalRegistry)
            .build()

        harness.runAndLogOnFailure {
            // ACT
            harness.store.dispatch("ui", Action("fakea.ALLOWED"))
            harness.store.dispatch("ui", Action("core.SET_ACTIVE_VIEW")) // Valid in real registry, but not in our override

            // ASSERT
            assertEquals(1, harness.processedActions.size, "Only the action in the minimal registry should pass.")
            assertEquals("fakea.ALLOWED", harness.processedActions.first().name)
            val log = harness.platform.capturedLogs.find { it.message.contains("Unknown Action 'core.SET_ACTIVE_VIEW'") }
            assertNotNull(log, "The store should block an action not present in the override set.")
        }
    }
}